version: "3.1"

services:
  db_server:
    image: ${DB:-mariadb:10.3}
    environment:
      MYSQL_ROOT_PASSWORD: "${TESTSUITE_PASSWORD:-my-secret-pw}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${TESTSUITE_PASSWORD:-my-secret-pw}"]
      start_period: 10s
      interval: 5s
      timeout: 60s
      retries: 10
    networks:
      testing:
        aliases:
         - ecdb_testing_db
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=300m

  ecdb:
    build:
      context: ../../apache
    environment:
      ECDB_HOST: db_server
      UPLOAD_LIMIT: 123M
      MAX_EXECUTION_TIME: 125
      HIDE_PHP_VERSION: 1
      ECDB_UPLOADDIR: /etc/ecdb/imports
      ECDB_SAVEDIR: /etc/ecdb/exports
    volumes:
      - ../config.user.inc.php:/etc/ecdb/config.user.inc.php:ro
      - ecdb-data:/etc/ecdb/imports:ro
      - ecdb-data:/etc/ecdb/exports
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      start_period: 5s
      interval: 3s
      timeout: 60s
      retries: 10
    networks:
      testing:
        aliases:
         - ecdb_testing_apache
    depends_on:
      db_server:
        condition: service_healthy

  sut:
    depends_on:
      ecdb:
        condition: service_healthy
      db_server:
        condition: service_healthy
    build:
      context: ../
    command: "/tests/testing/test-docker.sh"
    networks:
      testing:
    environment:
      TESTSUITE_HOSTNAME: ecdb_testing_apache
      TESTSUITE_PORT: 80
      TESTSUITE_PASSWORD: "${TESTSUITE_PASSWORD:-my-secret-pw}"
      ECDB_HOST: ecdb_testing_db
      ECDB_PORT: 3306
      ECDB_UPLOADDIR: /etc/ecdb/imports
      ECDB_SAVEDIR: /etc/ecdb/exports
    volumes:
      - ../../:/tests:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ecdb-data:/etc/ecdb/imports
      - ecdb-data:/etc/ecdb/exports
    working_dir: /tests

networks:
    testing:
        driver: bridge

volumes:
  ecdb-data:
